---------------------------------------------------------------
-- Copyright (C) 2012-2014 Luleå University of Technology
-- All rights reserved.
---------------------------------------------------------------
-- Created: 2012-09-24 G�ran Lindqvist LDB-Centrum / LTU
-- Modified:
---------------------------------------------------------------
-- Template for add information to tbl: PPE_OPINIONS
-- V1 => PROVIDERID, example: Amazon 
-- V2 => SYSTEMID, example: S3
-- X => ASSESSMENT, example: (1 ,0 , NULL)

---------------------------------------------------------------
--Plugin:
---------------------------------------------------------------
--Start
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT) 
 VALUES ('V1', 'V2', '3.1.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.1.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.1.2.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT) 
 VALUES ('V1', 'V2', '3.1.2.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.1.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.2.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.2.1.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.2.1.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.2.1.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.3.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.3.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.3.2.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.3.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.3.4', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.3.5', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.3.6', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.5.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.5.1.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.5.1.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.5.1.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.5.1.4', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '3.5.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.1.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.1.1.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.1.1.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.1.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.1.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.1.4', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.1.5', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.1.6', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.1.7', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.1.8', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.1.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.1.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.3.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.4', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.4.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.4.1.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.4.1.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.4.1.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.4.1.4', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.4.1.5', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.4.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.5', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.5.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.5.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.5.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.5.4', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.6', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.6.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.6.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.6.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.7', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.7.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.7.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.7.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.8', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.9', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.2.10', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.3.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.3.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.3.2.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.3.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.3.3.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.3.4', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.4.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.4.1.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.4.1.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.4.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.4.2.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.4.2.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.5.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.5.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.5.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.5.3.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.6.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.6.1.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.6.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '4.6.2.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.1.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.1.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.1.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.1.4', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.1.5', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.1.6', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.1.7', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.1.8', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.3.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.4', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.5', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.6', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.6.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.1.6.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.1.2.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.2.1', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.2.2', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.2.3', X);
INSERT INTO PPE_OPINIONS (PROVIDERID, SYSTEMID, ASSESSMENTID, ASSESSMENT)
 VALUES ('V1', 'V2', '5.2.4', X);
--End
